spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: outbox
    password: 12345

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  error:
    include-message: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
