spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/outbox
    username: outbox
    password: 12345

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092

server:
  error:
    include-message: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

outbox:
  batch-size: 10
  pull-outbox-events-rate: 5000
  kafka-defaults:
    topic-name: messages
    topic-replication-factor: 3
    topic-partitions-number: 3
    poll-timeout: 3000
    linger-ms: 20